class CFG:
    PATH_REAL_IMAGES = r"D:\facultate\An 3\LICENTA\dataset\real images"
    PATH_ABSTRACT_IMAGES = r"D:\facultate\An 3\LICENTA\dataset\abstract scenes"

    REAL_TRAIN_IMAGES_PATH = PATH_REAL_IMAGES + r"\train\train2014"
    REAL_TRAIN_QUESTIONS_PATH = PATH_REAL_IMAGES + r"\train\OpenEnded_mscoco_train2014_questions.json"
    REAL_TRAIN_MultipleChoice_PATH = PATH_REAL_IMAGES + r"\train\MultipleChoice_mscoco_train2014_questions.json"
    REAL_TRAIN_ANNOTATIONS_PATH = PATH_REAL_IMAGES + r"\train\mscoco_train2014_annotations.json"

    REAL_VAL_IMAGES_PATH = PATH_REAL_IMAGES + r"\validation\val2014"
    REAL_VAL_QUESTIONS_PATH = PATH_REAL_IMAGES + r"\validation\OpenEnded_mscoco_val2014_questions.json"
    REAL_VAL_MultipleChoice_PATH = PATH_REAL_IMAGES + r"\validation\MultipleChoice_mscoco_val2014_questions.json"
    REAL_VAL_ANNOTATIONS_PATH = PATH_REAL_IMAGES + r"\validation\mscoco_val2014_annotations.json"

    ABSTRACT_TRAIN_IMAGES_PATH = PATH_ABSTRACT_IMAGES + r"\train\train_images"
    ABSTRACT_TRAIN_QUESTIONS_PATH = PATH_ABSTRACT_IMAGES + r"\train\OpenEnded_abstract_v002_train2015_questions.json"
    ABSTRACT_TRAIN_MultipleChoice_PATH = PATH_ABSTRACT_IMAGES + r"\train\MultipleChoice_abstract_v002_train2015_questions.json"
    ABSTRACT_TRAIN_ANNOTATIONS_PATH = PATH_ABSTRACT_IMAGES + r"\train\abstract_v002_train2015_annotations.json"

    ABSTRACT_VAL_IMAGES_PATH = PATH_ABSTRACT_IMAGES + r"\validation\val_images"
    ABSTRACT_VAL_QUESTIONS_PATH = PATH_ABSTRACT_IMAGES + r"\validation\OpenEnded_abstract_v002_val2015_questions.json"
    ABSTRACT_VAL_MultipleChoice_PATH = PATH_ABSTRACT_IMAGES + r"\validation\MultipleChoice_abstract_v002_val2015_questions.json"
    ABSTRACT_VAL_ANNOTATIONS_PATH = PATH_ABSTRACT_IMAGES + r"\validation\abstract_v002_val2015_annotations.json"

    PATH_EMBEDDINGS_REAL_ANSWERS_TRAIN = r"D:\facultate\An 3\LICENTA\dataset\all_embeddings\real\real answers train"
    PATH_EMBEDDINGS_REAL_ANSWERS_VALIDATION = r"D:\facultate\An 3\LICENTA\dataset\all_embeddings\real\real answers validation"
    PATH_EMBEDDINGS_REAL_IMAGES_TRAIN = r"D:\facultate\An 3\LICENTA\dataset\all_embeddings\real\real images train"
    PATH_EMBEDDINGS_REAL_IMAGES_VALIDATION = r"D:\facultate\An 3\LICENTA\dataset\all_embeddings\real\real images validation"
    PATH_EMBEDDINGS_REAL_QUESTIONS_TRAIN = r"D:\facultate\An 3\LICENTA\dataset\all_embeddings\real\real questions train"
    PATH_EMBEDDINGS_REAL_QUESTIONS_VALIDATION = r"D:\facultate\An 3\LICENTA\dataset\all_embeddings\real\real questions validation"

    PATH_EMBEDDINGS_ABSTRACT_ANSWERS_TRAIN = r"D:\facultate\An 3\LICENTA\dataset\all_embeddings\abstract\abstract answers train"
    PATH_EMBEDDINGS_ABSTRACT_ANSWERS_VALIDATION = r"D:\facultate\An 3\LICENTA\dataset\all_embeddings\abstract\abstract answers validation"
    PATH_EMBEDDINGS_ABSTRACT_IMAGES_TRAIN = r"D:\facultate\An 3\LICENTA\dataset\all_embeddings\abstract\abstract images train"
    PATH_EMBEDDINGS_ABSTRACT_IMAGES_VALIDATION = r"D:\facultate\An 3\LICENTA\dataset\all_embeddings\abstract\abstract images validation"
    PATH_EMBEDDINGS_ABSTRACT_QUESTIONS_TRAIN = r"D:\facultate\An 3\LICENTA\dataset\all_embeddings\abstract\abstract questions train"
    PATH_EMBEDDINGS_ABSTRACT_QUESTIONS_VALIDATION = r"D:\facultate\An 3\LICENTA\dataset\all_embeddings\abstract\abstract questions validation"

    PATH_TRAIN_RESNET50_MS_COCO_V2_IMAGES = r"D:\facultate\An 3\LICENTA\dataset\img\train_resnet50"
    PATH_TRAIN_REGNETY_MS_COCO_V2_IMAGES = r"D:\facultate\An 3\LICENTA\dataset\img\train_regnety"
    PATH_TRAIN_SSL_RESNET50_MS_COCO_V2_IMAGES = r"D:\facultate\An 3\LICENTA\dataset\img\train_ssl"
    PATH_TRAIN_SWIN_TINY_MS_COCO_V2_IMAGES = r"D:\facultate\An 3\LICENTA\dataset\img\train_swin"
    PATH_TRAIN_RESNEST50D_MS_COCO_V2_IMAGES = r"D:\facultate\An 3\LICENTA\dataset\img\train_resnest"
    PATH_TRAIN_CONVNEXT_TINY_MS_COCO_V2_IMAGES = r"D:\facultate\An 3\LICENTA\dataset\img\train_convnext"

    PATH_VAL_RESNET50_MS_COCO_V2_IMAGES = r"D:\facultate\An 3\LICENTA\dataset\img\val_resnet50"
    PATH_VAL_REGNETY_MS_COCO_V2_IMAGES = r"D:\facultate\An 3\LICENTA\dataset\img\val_regnety"
    PATH_VAL_SSL_RESNET50_MS_COCO_V2_IMAGES = r"D:\facultate\An 3\LICENTA\dataset\img\val_ssl"
    PATH_VAL_SWIN_TINY_MS_COCO_V2_IMAGES = r"D:\facultate\An 3\LICENTA\dataset\img\val_swin"
    PATH_VAL_RESNEST50D_MS_COCO_V2_IMAGES = r"D:\facultate\An 3\LICENTA\dataset\img\val_resnest"
    PATH_VAL_CONVNEXT_TINY_MS_COCO_V2_IMAGES = r"D:\facultate\An 3\LICENTA\dataset\img\val_convnext"

    PATH_TRAIN_RESNET50_MS_COCO_V2_TEXT = r"D:\facultate\An 3\LICENTA\dataset\lang\train_resnet50"
    PATH_TRAIN_REGNETY_MS_COCO_V2_TEXT = r"D:\facultate\An 3\LICENTA\dataset\lang\train_regnety"
    PATH_TRAIN_SSL_RESNET50_MS_COCO_V2_TEXT = r"D:\facultate\An 3\LICENTA\dataset\lang\train_ssl"
    PATH_TRAIN_SWIN_TINY_MS_COCO_V2_TEXT = r"D:\facultate\An 3\LICENTA\dataset\lang\train_swin"
    PATH_TRAIN_RESNEST50D_MS_COCO_V2_TEXT = r"D:\facultate\An 3\LICENTA\dataset\lang\train_resnest"
    PATH_TRAIN_CONVNEXT_TINY_MS_COCO_V2_TEXT = r"D:\facultate\An 3\LICENTA\dataset\lang\train_convnext"

    PATH_VAL_RESNET50_MS_COCO_V2_TEXT = r"D:\facultate\An 3\LICENTA\dataset\lang\val_resnet50"
    PATH_VAL_REGNETY_MS_COCO_V2_TEXT = r"D:\facultate\An 3\LICENTA\dataset\lang\val_regnety"
    PATH_VAL_SSL_RESNET50_MS_COCO_V2_TEXT = r"D:\facultate\An 3\LICENTA\dataset\lang\val_ssl"
    PATH_VAL_SWIN_TINY_MS_COCO_V2_TEXT = r"D:\facultate\An 3\LICENTA\dataset\lang\val_swin"
    PATH_VAL_RESNEST50D_MS_COCO_V2_TEXT = r"D:\facultate\An 3\LICENTA\dataset\lang\val_resnest"
    PATH_VAL_CONVNEXT_TINY_MS_COCO_V2_TEXT = r"D:\facultate\An 3\LICENTA\dataset\lang\val_convnext"